#!/bin/bash                                                                                                                                                                    
FLAGMATIC_PKG=/Users/srobik/Github/flagmatic-2.0/pkg/
SAGE_SITE_PKGS=/Users/srobik/sage/sage/local/lib/python2.7/site-packages/

# remove old flagmatic versions                                                                                                                                                
cd $SAGE_SITE_PKGS
eval "sudo rm Flagmatic*.egg-info"
eval "sudo rm -rf flagmatic"

# install new flagmatic version                                                                                                                                                
cd $FLAGMATIC_PKG
eval "sudo -E sage -python setup.py install"
